// Palette data from the installed Codex visual-style presets.
export const codexThemes = [
  {
    name: "Absolutely",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-absolutely-dark",
        background: "#2d2d2b",
        foreground: "#f9f9f7",
        sidebar: "#373735",
        sidebarForeground: "#f9f9f7",
        accent: "#cc7d5e",
        source: "absolutely-dark-f50f351ee0a4.js",
      },
      light: {
        id: "codex-absolutely-light",
        background: "#f9f9f7",
        foreground: "#2d2d2b",
        sidebar: "#f4f4f2",
        sidebarForeground: "#2d2d2b",
        accent: "#cc7d5e",
        source: "absolutely-light-79eaa93587de.js",
      },
    },
  },
  {
    name: "Ayu",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-ayu-dark",
        background: "#10141c",
        foreground: "#bfbdb6",
        sidebar: "#0d1017",
        sidebarForeground: "#bfbdb6",
        accent: "#e6b450",
        source: "ayu-dark-caa06d477d0a.js",
      },
    },
  },
  {
    name: "Catppuccin",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-catppuccin-dark",
        background: "#1e1e2e",
        foreground: "#cdd6f4",
        sidebar: "#181825",
        sidebarForeground: "#cdd6f4",
        accent: "#89b4fa",
        source: "catppuccin-mocha-1eac89cf4105.js",
      },
      light: {
        id: "codex-catppuccin-light",
        background: "#eff1f5",
        foreground: "#4c4f69",
        sidebar: "#e6e9ef",
        sidebarForeground: "#4c4f69",
        accent: "#1e66f5",
        source: "catppuccin-latte-943235df260d.js",
      },
    },
  },
  {
    name: "Codex",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-codex-dark",
        background: "#111111",
        foreground: "#fcfcfc",
        sidebar: "#131313",
        sidebarForeground: "#8f8f8f",
        accent: "#0169cc",
        source: "codex-dark-5fb95d1c65ca.js",
      },
      light: {
        id: "codex-codex-light",
        background: "#ffffff",
        foreground: "#0d0d0d",
        sidebar: "#fcfcfc",
        sidebarForeground: "#212121",
        accent: "#0169cc",
        source: "codex-light-53d4e35e1869.js",
      },
    },
  },
  {
    name: "Dracula",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-dracula-dark",
        background: "#282A36",
        foreground: "#F8F8F2",
        sidebar: "#21222C",
        sidebarForeground: "#F8F8F2",
        accent: "#44475A",
        source: "dracula-8ebb6e65aee6.js",
      },
    },
  },
  {
    name: "Everforest",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-everforest-dark",
        background: "#2d353b",
        foreground: "#d3c6aa",
        sidebar: "#2d353b",
        sidebarForeground: "#859289",
        accent: "#a7c080",
        source: "everforest-dark-483f6d991548.js",
      },
      light: {
        id: "codex-everforest-light",
        background: "#fdf6e3",
        foreground: "#5c6a72",
        sidebar: "#fdf6e3",
        sidebarForeground: "#939f91",
        accent: "#8da101",
        source: "everforest-light-18283206f02c.js",
      },
    },
  },
  {
    name: "GitHub",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-github-dark",
        background: "#0d1117",
        foreground: "#e6edf3",
        sidebar: "#010409",
        sidebarForeground: "#e6edf3",
        accent: "#2f81f7",
        source: "github-dark-default-b8e70e64710b.js",
      },
      light: {
        id: "codex-github-light",
        background: "#ffffff",
        foreground: "#1f2328",
        sidebar: "#f6f8fa",
        sidebarForeground: "#1f2328",
        accent: "#0969da",
        source: "github-light-default-17c4595cade8.js",
      },
    },
  },
  {
    name: "Gruvbox",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-gruvbox-dark",
        background: "#282828",
        foreground: "#ebdbb2",
        sidebar: "#282828",
        sidebarForeground: "#d5c4a1",
        accent: "#83a598",
        source: "gruvbox-dark-medium-8ca3a11da780.js",
      },
      light: {
        id: "codex-gruvbox-light",
        background: "#fbf1c7",
        foreground: "#3c3836",
        sidebar: "#fbf1c7",
        sidebarForeground: "#504945",
        accent: "#076678",
        source: "gruvbox-light-medium-a0d95c5132f1.js",
      },
    },
  },
  {
    name: "Linear",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-linear-dark",
        background: "#17181d",
        foreground: "#e6e9ef",
        sidebar: "#080a0f",
        sidebarForeground: "#d8dce6",
        accent: "#5e6ad2",
        source: "linear-dark-f292b3b1106f.js",
      },
      light: {
        id: "codex-linear-light",
        background: "#f7f8fa",
        foreground: "#2a3140",
        sidebar: "#f2f4f8",
        sidebarForeground: "#4a5263",
        accent: "#5e6ad2",
        source: "linear-light-68b2f60d891c.js",
      },
    },
  },
  {
    name: "Lobster",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-lobster-dark",
        background: "#111827",
        foreground: "#e4e4e7",
        sidebar: "#111827",
        sidebarForeground: "#e4e4e7",
        accent: "#ff5c5c",
        source: "lobster-dark-3c7e0b666bb2.js",
      },
    },
  },
  {
    name: "Material",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-material-dark",
        background: "#212121",
        foreground: "#EEFFFF",
        sidebar: "#212121",
        sidebarForeground: "#676767",
        accent: "#80CBC4",
        source: "material-theme-darker-578f7701bce7.js",
      },
    },
  },
  {
    name: "Matrix",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-matrix-dark",
        background: "#040805",
        foreground: "#b8ffca",
        sidebar: "#020402",
        sidebarForeground: "#9bffb8",
        accent: "#1eff5a",
        source: "matrix-dark-fa9710869ce4.js",
      },
    },
  },
  {
    name: "Monokai",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-monokai-dark",
        background: "#272822",
        foreground: "#f8f8f2",
        sidebar: "#1e1f1c",
        sidebarForeground: "#f8f8f2",
        accent: "#75715E",
        source: "monokai-34b7c8264728.js",
      },
    },
  },
  {
    name: "Night Owl",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-night-owl-dark",
        background: "#011627",
        foreground: "#d6deeb",
        sidebar: "#011627",
        sidebarForeground: "#89a4bb",
        accent: "#7e57c2cc",
        source: "night-owl-9523f1771173.js",
      },
    },
  },
  {
    name: "Nord",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-nord-dark",
        background: "#2e3440",
        foreground: "#d8dee9",
        sidebar: "#2e3440",
        sidebarForeground: "#d8dee9",
        accent: "#88c0d0",
        source: "nord-1e5b8199cbad.js",
      },
    },
  },
  {
    name: "Notion",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-notion-dark",
        background: "#191919",
        foreground: "#d9d9d8",
        sidebar: "#151515",
        sidebarForeground: "#d9d9d8",
        accent: "#3183d8",
        source: "notion-dark-53bed5670fb6.js",
      },
      light: {
        id: "codex-notion-light",
        background: "#ffffff",
        foreground: "#37352f",
        sidebar: "#f7f6f3",
        sidebarForeground: "#4f4b45",
        accent: "#3183d8",
        source: "notion-light-616fcde10962.js",
      },
    },
  },
  {
    name: "OG",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-og-dark",
        background: "#343541",
        foreground: "#d1d5db",
        sidebar: "#202123",
        sidebarForeground: "#ececf1",
        accent: "#10a37f",
        source: "og-dark-c4ffd9f0861f.js",
      },
    },
  },
  {
    name: "One",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-one-dark",
        background: "#282c34",
        foreground: "#abb2bf",
        sidebar: "#21252b",
        sidebarForeground: "#abb2bf",
        accent: "#61afef",
        source: "one-dark-pro-a86e56242366.js",
      },
      light: {
        id: "codex-one-light",
        background: "#FAFAFA",
        foreground: "#383A42",
        sidebar: "#EAEAEB",
        sidebarForeground: "#383A42",
        accent: "#5871EF",
        source: "one-light-10859d10bab4.js",
      },
    },
  },
  {
    name: "Oscurange",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-oscurange-dark",
        background: "#0B0B0F",
        foreground: "#E6E6E6",
        sidebar: "#0B0B0F",
        sidebarForeground: "#E6E6E6",
        accent: "#d8dee9ff",
        source: "oscurange-8a344130cdcd.js",
      },
    },
  },
  {
    name: "Proof",
    modes: ["light"],
    variants: {
      light: {
        id: "codex-proof-light",
        background: "#f5f3ed",
        foreground: "#2f312d",
        sidebar: "#efede6",
        sidebarForeground: "#4b4d48",
        accent: "#3d755d",
        source: "proof-light-818ee16fd59b.js",
      },
    },
  },
  {
    name: "Raycast",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-raycast-dark",
        background: "#141414",
        foreground: "#FFFFFF",
        sidebar: "#101010",
        sidebarForeground: "#FFFFFF99",
        accent: "#4FA3F8",
        source: "raycast-dark-d8918c2e5e09.js",
      },
      light: {
        id: "codex-raycast-light",
        background: "#FFFFFF",
        foreground: "#000000",
        sidebar: "#fcfcfc",
        sidebarForeground: "#00000099",
        accent: "#138AF2",
        source: "raycast-light-b4a56c15bc92.js",
      },
    },
  },
  {
    name: "Rose Pine",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-rose-pine-dark",
        background: "#232136",
        foreground: "#e0def4",
        sidebar: "#232136",
        sidebarForeground: "#908caa",
        accent: "#c4a7e7",
        source: "rose-pine-moon-fc3e86b295eb.js",
      },
      light: {
        id: "codex-rose-pine-light",
        background: "#faf4ed",
        foreground: "#575279",
        sidebar: "#faf4ed",
        sidebarForeground: "#797593",
        accent: "#907aa9",
        source: "rose-pine-dawn-107da88ae0d9.js",
      },
    },
  },
  {
    name: "Sentry",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-sentry-dark",
        background: "#2d2935",
        foreground: "#e6dff9",
        sidebar: "#26222d",
        sidebarForeground: "#d5cdee",
        accent: "#7055f6",
        source: "sentry-dark-3f32975f372b.js",
      },
    },
  },
  {
    name: "Solarized",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-solarized-dark",
        background: "#002B36",
        foreground: "#839496",
        sidebar: "#00212B",
        sidebarForeground: "#839496",
        accent: "#2AA19899",
        source: "solarized-dark-b35bc77018b4.js",
      },
      light: {
        id: "codex-solarized-light",
        background: "#FDF6E3",
        foreground: "#657B83",
        sidebar: "#EEE8D5",
        sidebarForeground: "#657B83",
        accent: "#AC9D57",
        source: "solarized-light-de3cb543368f.js",
      },
    },
  },
  {
    name: "Temple",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-temple-dark",
        background: "#02120c",
        foreground: "#c7e6da",
        sidebar: "#1d2d0f",
        sidebarForeground: "#c7e6da",
        accent: "#e4f222",
        source: "temple-dark-9eae56d88ac5.js",
      },
    },
  },
  {
    name: "Tokyo Night",
    modes: ["dark"],
    variants: {
      dark: {
        id: "codex-tokyo-night-dark",
        background: "#1a1b26",
        foreground: "#a9b1d6",
        sidebar: "#16161e",
        sidebarForeground: "#787c99",
        accent: "#6183bb",
        source: "tokyo-night-5c1ab4ec610d.js",
      },
    },
  },
  {
    name: "Vercel",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-vercel-dark",
        background: "#000000",
        foreground: "#ededed",
        sidebar: "#000000",
        sidebarForeground: "#a1a1a1",
        accent: "#006efe",
        source: "vercel-dark-fe3b20ba4c28.js",
      },
      light: {
        id: "codex-vercel-light",
        background: "#ffffff",
        foreground: "#171717",
        sidebar: "#ffffff",
        sidebarForeground: "#666666",
        accent: "#006aff",
        source: "vercel-light-91ea99803eaa.js",
      },
    },
  },
  {
    name: "VS Code Plus",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-vscode-plus-dark",
        background: "#1E1E1E",
        foreground: "#D4D4D4",
        sidebar: "#1E1E1E",
        sidebarForeground: "#D4D4D4",
        accent: "#D4D4D4",
        source: "dark-plus-25b7adc7cc07.js",
      },
      light: {
        id: "codex-vscode-plus-light",
        background: "#FFFFFF",
        foreground: "#000000",
        sidebar: "#FFFFFF",
        sidebarForeground: "#000000",
        accent: "#000000ff",
        source: "light-plus-3813864be474.js",
      },
    },
  },
  {
    name: "Xcode",
    modes: ["dark", "light"],
    variants: {
      dark: {
        id: "codex-xcode-dark",
        background: "#1f1f24",
        foreground: "#ffffffd9",
        sidebar: "#1f1f24",
        sidebarForeground: "#ffffffd9",
        accent: "#5482ff",
        source: "xcode-dark-70031158a53b.js",
      },
      light: {
        id: "codex-xcode-light",
        background: "#ffffff",
        foreground: "#000000d9",
        sidebar: "#ffffff",
        sidebarForeground: "#000000d9",
        accent: "#0e0eff",
        source: "xcode-light-ad6a361cdfec.js",
      },
    },
  },
];
